version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8084:8084"
    links:
      - mongo
    tty: true
   
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    tty: true